### PR TITLE
Fix for #16 

### PR DESCRIPTION
**Pull request by theSloopJohnB**
No we get a better error - checkout the issue for the new and improved message.
Tested it out on my machine - works well.

### CODE REVIEW

**Comment by theSloopJohnB** [comment]
A proper link to #16 so I don't forget to close it later.

**Comment by theSloopJohnB** [comment]
Consolidated the validation for more useful errors, refactored the resolve VI to be simpler and less redundant (since validation already occurred) and added a test for my validation. This PR is ready for a new review.

**Comment by theSloopJohnB** [comment]
Thanks for double checking. There were a few things to patch up with respect to the classes. It should be good to go now.

**Comment by pollockm** [comment]
Running integration tests now.  If those pass, seems ready to go in.

**Comment by pollockm** [comment]
@theSloopJohnB Merged!   Please delete the branch.

**Pull request merged**
